services:
  db:
    container_name: mysql_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db-passwd
      MYSQL_PASSWORD: s9cre93
      MYSQL_USER: analitic
      MYSQL_DATABASE: iot_data
    volumes:
      - ./docker/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql_data:/docker-entrypoint-initdb.d
      - ./docker/mysql:/var/lib/mysql
    networks:
      - backnet
    secrets:
      - db-passwd
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    
  backend:
    build: ./iot_stats
    container_name: python_backend
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - frontnet
secrets:
  db-passwd:
    file: docker/db-passwd.txt

networks:
  backnet:
  frontnet: